'use client';

import { useParams } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { GitPullRequest, ExternalLink, Clock } from 'lucide-react';
import { getPullRequests } from '@/lib/api/scans';
import { SkeletonCard } from '@/components/ui/SkeletonCard';
import { EmptyState } from '@/components/ui/EmptyState';
import { relativeTime } from '@/lib/utils/formatters';

export default function PRGuardianPage() {
    const params = useParams();
    const scanId = params.id as string;

    const { data: prs, isLoading } = useQuery({
        queryKey: ['pull-requests'],
        queryFn: () => getPullRequests(),
    });

    if (isLoading) {
        return (
            <div className="space-y-4 max-w-[1000px]">
                {Array.from({ length: 3 }).map((_, i) => <SkeletonCard key={i} className="h-24" />)}
            </div>
        );
    }

    // Filter PRs by current scan if needed, or show all for this user.
    // The endpoint returns all PRs for the user. We'll show PRs for this scan, 
    // or all PRs if scanId is somewhat generic (like we might want to see them all).
    // For now, let's filter by scanId if we are inside a specific scan view.
    const scanPRs = prs?.filter((pr) => pr.scan_id === scanId) ?? [];

    return (
        <motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-6 max-w-[1000px]"
        >
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-lg font-semibold text-text-1">PR Guardian</h1>
                    <p className="text-xs text-text-2">Manage Pull Requests generated by CodeDebt Guardian</p>
                </div>
                <div className="px-3 py-1 bg-brand-dim text-brand rounded-full text-xs font-medium">
                    {scanPRs.length} PR{scanPRs.length === 1 ? '' : 's'} Created
                </div>
            </div>

            {scanPRs.length === 0 ? (
                <EmptyState
                    icon={GitPullRequest}
                    title="No PRs for this scan"
                    description="Run autopilot or manually create PRs from the Fixes tab"
                />
            ) : (
                <div className="space-y-3">
                    {scanPRs.map((pr) => (
                        <div
                            key={pr.id}
                            className="bg-bg-card border border-border rounded-xl p-4 flex items-center justify-between group hover:border-brand/30 transition-colors"
                        >
                            <div className="flex items-start gap-3">
                                <div className="p-2 bg-brand/10 rounded-lg">
                                    <GitPullRequest className="w-5 h-5 text-brand" />
                                </div>
                                <div>
                                    <h3 className="text-sm font-medium text-text-1 group-hover:text-brand transition-colors">
                                        {pr.title}
                                    </h3>
                                    <div className="flex items-center gap-3 mt-1 text-xs text-text-3">
                                        <span className="font-mono">#{pr.pr_number}</span>
                                        <span className="flex items-center gap-1">
                                            <Clock className="w-3 h-3" />
                                            {relativeTime(pr.created_at)}
                                        </span>
                                        <span className="px-1.5 py-0.5 rounded-full bg-bg-card-2 text-[10px] uppercase font-semibold">
                                            {pr.status}
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <a
                                href={pr.pr_url}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-bg-card-2 text-text-2 hover:bg-brand hover:text-white text-xs font-medium transition-colors"
                            >
                                View on GitHub
                                <ExternalLink className="w-3.5 h-3.5" />
                            </a>
                        </div>
                    ))}
                </div>
            )}
        </motion.div>
    );
}
